### ISSUE TITLE
Dropping the domain

### ISSUE THREAD

**Issue by OrkoHunter** [BinPy/binpy.github.com#4]
Since awhile the domain www.binpy.org has expired. Should we not stop redirecting to the site for some time and use [binpy.github.io](http://binpy.github.io) instead?
PS: I feel the need mainly because of the ideas page.

**Comment by debugger22** [comment]
Yes. Go ahead.

**Comment by debugger22** [comment]
Fixed by https://github.com/BinPy/binpy.github.com/pull/5
