### ISSUE TITLE
binpy.org domain registered by some other organization

### ISSUE THREAD

**Issue by aktech** [BinPy/binpy.github.com#7]
The domain has been registered by someone else, so it's not a good idea to point to this domain now.
docs.binpy.org as well.

@debugger22

**Comment by debugger22** [comment]
Yeah. I'll try to change that. Thanks for letting me know.

**Comment by OrkoHunter** [comment]
Done! Thanks @aktech .

**Comment by aktech** [comment]
Thanks!
Though I see http://binpy.github.io/ still mentions the http://docs.binpy.org/dev under Read the documentation.
